// Licensed to Elasticsearch B.V under one or more agreements.
// Elasticsearch B.V licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information

using Elastic.Changelog.Rendering;
using Elastic.Documentation.Diagnostics;
using FluentAssertions;

namespace Elastic.Changelog.Tests.Changelogs.Render;

public class BundleValidationTests(ITestOutputHelper output) : RenderChangelogTestBase(output)
{
	// language=yaml
	private const string ChangelogFeature1 =
		"""
		title: Feature one
		type: feature
		products:
		  - product: elasticsearch
		    target: 9.2.0
		prs:
		- "101"
		""";

	// language=yaml
	private const string ChangelogFeature2 =
		"""
		title: Feature two
		type: enhancement
		products:
		  - product: elasticsearch
		    target: 9.2.0
		prs:
		- "102"
		""";

	// language=yaml
	private const string ChangelogFeature3 =
		"""
		title: Feature three
		type: bug-fix
		products:
		  - product: elasticsearch
		    target: 9.2.0
		prs:
		- "103"
		""";

	// language=yaml
	private const string ChangelogWithComments =
		"""
		# This is a generated changelog entry
		# Do not edit this file directly
		title: Commented feature
		type: feature
		products:
		  - product: elasticsearch
		    target: 9.2.0
		prs:
		- "104"
		""";

	// language=yaml
	private const string ChangelogDifferentData =
		"""
		title: Completely different feature
		type: enhancement
		products:
		  - product: kibana
		    target: 9.2.0
		prs:
		- "999"
		""";

	[Fact]
	public async Task MultipleAmendFiles_AllEntriesMergedAndRendered()
	{
		// Arrange — main bundle with 1 entry + 2 amend files with 1 entry each
		var (bundleDir, changelogDir) = CreateTestDirs();

		var file1 = "1000000001-feature.yaml";
		var file2 = "1000000002-enhancement.yaml";
		var file3 = "1000000003-bugfix.yaml";
		await WriteFileAsync(changelogDir, file1, ChangelogFeature1);
		await WriteFileAsync(changelogDir, file2, ChangelogFeature2);
		await WriteFileAsync(changelogDir, file3, ChangelogFeature3);

		// Main bundle references file1
		var bundleFile = FileSystem.Path.Combine(bundleDir, "bundle.yaml");
		await WriteBundleAsync(bundleFile, file1, ComputeSha1(ChangelogFeature1));

		// Amend-1 references file2
		var amend1 = FileSystem.Path.Combine(bundleDir, "bundle.amend-1.yaml");
		await WriteBundleAsync(amend1, file2, ComputeSha1(ChangelogFeature2));

		// Amend-2 references file3
		var amend2 = FileSystem.Path.Combine(bundleDir, "bundle.amend-2.yaml");
		await WriteBundleAsync(amend2, file3, ComputeSha1(ChangelogFeature3));

		var input = CreateRenderInput(bundleFile, changelogDir);

		// Act
		var result = await Service.RenderChangelogs(Collector, input, TestContext.Current.CancellationToken);

		// Assert
		result.Should().BeTrue();
		Collector.Errors.Should().Be(0);
		Collector.Warnings.Should().Be(0, "all checksums match, no warnings expected");

		// Verify all 3 entries were rendered
		var indexFile = FileSystem.Path.Combine(input.Output!, "9.2.0", "index.md");
		FileSystem.File.Exists(indexFile).Should().BeTrue("output should be rendered");
		var content = await FileSystem.File.ReadAllTextAsync(indexFile, TestContext.Current.CancellationToken);
		content.Should().Contain("Feature one");
		content.Should().Contain("Feature two");
		content.Should().Contain("Feature three");
	}

	[Fact]
	public async Task AmendFileEntry_WithMatchingChecksum_NoWarning()
	{
		// Arrange — amend file has a file reference with correct normalized checksum
		var (bundleDir, changelogDir) = CreateTestDirs();

		var file1 = "1000000001-feature.yaml";
		var file2 = "1000000002-enhancement.yaml";
		await WriteFileAsync(changelogDir, file1, ChangelogFeature1);
		await WriteFileAsync(changelogDir, file2, ChangelogFeature2);

		var bundleFile = FileSystem.Path.Combine(bundleDir, "bundle.yaml");
		await WriteBundleAsync(bundleFile, file1, ComputeSha1(ChangelogFeature1));

		var amend1 = FileSystem.Path.Combine(bundleDir, "bundle.amend-1.yaml");
		await WriteBundleAsync(amend1, file2, ComputeSha1(ChangelogFeature2));

		var input = CreateRenderInput(bundleFile, changelogDir);

		// Act
		var result = await Service.RenderChangelogs(Collector, input, TestContext.Current.CancellationToken);

		// Assert
		result.Should().BeTrue();
		Collector.Warnings.Should().Be(0, "amend entry checksum matches file on disk");
	}

	[Fact]
	public async Task AmendFileEntry_WithMismatchedChecksum_EmitsActionableWarning()
	{
		// Arrange — amend file has a file reference whose checksum doesn't match the file on disk
		var (bundleDir, changelogDir) = CreateTestDirs();

		var file1 = "1000000001-feature.yaml";
		var file2 = "1000000002-enhancement.yaml";
		await WriteFileAsync(changelogDir, file1, ChangelogFeature1);
		await WriteFileAsync(changelogDir, file2, ChangelogDifferentData); // Different content!

		var bundleFile = FileSystem.Path.Combine(bundleDir, "bundle.yaml");
		await WriteBundleAsync(bundleFile, file1, ComputeSha1(ChangelogFeature1));

		// Amend stores checksum of ChangelogFeature2 but file on disk has ChangelogDifferentData
		var amend1 = FileSystem.Path.Combine(bundleDir, "bundle.amend-1.yaml");
		await WriteBundleAsync(amend1, file2, ComputeSha1(ChangelogFeature2));

		var input = CreateRenderInput(bundleFile, changelogDir);

		// Act
		var result = await Service.RenderChangelogs(Collector, input, TestContext.Current.CancellationToken);

		// Assert
		result.Should().BeTrue("warnings don't prevent rendering");
		Collector.Warnings.Should().BeGreaterThan(0);
		Collector.Diagnostics.Should().Contain(d =>
			d.Severity == Severity.Warning &&
			d.Message.Contains("Checksum mismatch") &&
			d.Message.Contains("the file content has changed since it was bundled") &&
			d.Message.Contains("re-run 'bundle' or 'bundle-amend'") &&
			d.Message.Contains("--resolve"));
	}

	[Fact]
	public async Task AmendFileEntry_WithResolvedData_SkipsChecksumValidation()
	{
		// Arrange — amend file has a resolved entry (inline data), no file on disk needed
		var (bundleDir, changelogDir) = CreateTestDirs();

		var file1 = "1000000001-feature.yaml";
		await WriteFileAsync(changelogDir, file1, ChangelogFeature1);

		var bundleFile = FileSystem.Path.Combine(bundleDir, "bundle.yaml");
		await WriteBundleAsync(bundleFile, file1, ComputeSha1(ChangelogFeature1));

		// Amend with resolved entry (inline data, no file reference needed)
		var amend1 = FileSystem.Path.Combine(bundleDir, "bundle.amend-1.yaml");
		// language=yaml
		var amendContent =
			"""
			products: []
			entries:
			  - type: feature
			    title: Resolved amend feature
			    products:
			      - product: elasticsearch
			        target: 9.2.0
			    prs:
			    - "200"
			""";
		await FileSystem.File.WriteAllTextAsync(amend1, amendContent, TestContext.Current.CancellationToken);

		var input = CreateRenderInput(bundleFile, changelogDir);

		// Act
		var result = await Service.RenderChangelogs(Collector, input, TestContext.Current.CancellationToken);

		// Assert
		result.Should().BeTrue();
		Collector.Warnings.Should().Be(0, "resolved entries skip checksum validation");

		var indexFile = FileSystem.Path.Combine(input.Output!, "9.2.0", "index.md");
		var content = await FileSystem.File.ReadAllTextAsync(indexFile, TestContext.Current.CancellationToken);
		content.Should().Contain("Resolved amend feature");
	}

	[Fact]
	public async Task AmendFileEntry_CommentedFile_NormalizedChecksum_NoWarning()
	{
		// Arrange — amend stores normalized checksum, file on disk has comments
		var (bundleDir, changelogDir) = CreateTestDirs();

		var file1 = "1000000001-feature.yaml";
		var file2 = "1000000002-commented.yaml";
		await WriteFileAsync(changelogDir, file1, ChangelogFeature1);
		await WriteFileAsync(changelogDir, file2, ChangelogWithComments);

		var bundleFile = FileSystem.Path.Combine(bundleDir, "bundle.yaml");
		await WriteBundleAsync(bundleFile, file1, ComputeSha1(ChangelogFeature1));

		// Amend stores normalized checksum (comments are stripped before hashing)
		var amend1 = FileSystem.Path.Combine(bundleDir, "bundle.amend-1.yaml");
		await WriteBundleAsync(amend1, file2, ComputeSha1(ChangelogWithComments));

		var input = CreateRenderInput(bundleFile, changelogDir);

		// Act
		var result = await Service.RenderChangelogs(Collector, input, TestContext.Current.CancellationToken);

		// Assert
		result.Should().BeTrue();
		Collector.Warnings.Should().Be(0, "normalized checksum matches regardless of comments");
	}

	private (string BundleDir, string ChangelogDir) CreateTestDirs()
	{
		var bundleDir = FileSystem.Path.Combine(FileSystem.Path.GetTempPath(), Guid.NewGuid().ToString());
		var changelogDir = FileSystem.Path.Combine(FileSystem.Path.GetTempPath(), Guid.NewGuid().ToString());
		FileSystem.Directory.CreateDirectory(bundleDir);
		FileSystem.Directory.CreateDirectory(changelogDir);
		return (bundleDir, changelogDir);
	}

	private async Task WriteFileAsync(string dir, string fileName, string content) =>
		await FileSystem.File.WriteAllTextAsync(
			FileSystem.Path.Combine(dir, fileName), content, TestContext.Current.CancellationToken);

	private async Task WriteBundleAsync(string bundlePath, string entryFileName, string checksum)
	{
		// language=yaml
		var content =
			$"""
			products:
			  - product: elasticsearch
			    target: 9.2.0
			entries:
			  - file:
			      name: {entryFileName}
			      checksum: {checksum}
			""";
		await FileSystem.File.WriteAllTextAsync(bundlePath, content, TestContext.Current.CancellationToken);
	}

	private RenderChangelogsArguments CreateRenderInput(string bundleFile, string changelogDir) =>
		new()
		{
			Bundles = [new BundleInput { BundleFile = bundleFile, Directory = changelogDir }],
			Output = FileSystem.Path.Combine(FileSystem.Path.GetTempPath(), Guid.NewGuid().ToString()),
			Title = "9.2.0"
		};
}
