// Licensed to Elasticsearch B.V under one or more agreements.
// Elasticsearch B.V licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information

using Elastic.Changelog.Rendering;
using Elastic.Documentation.Diagnostics;
using FluentAssertions;

namespace Elastic.Changelog.Tests.Changelogs.Render;

public class ChecksumValidationTests(ITestOutputHelper output) : RenderChangelogTestBase(output)
{
	// language=yaml
	private const string ChangelogWithComments =
		"""
		# This is a generated changelog entry
		# Do not edit this file directly
		title: My new feature
		type: feature
		products:
		  - product: elasticsearch
		    target: 9.2.0
		prs:
		- "100"
		""";

	// language=yaml
	private const string ChangelogWithoutComments =
		"""
		title: My new feature
		type: feature
		products:
		  - product: elasticsearch
		    target: 9.2.0
		prs:
		- "100"
		""";

	// language=yaml
	private const string ChangelogWithDifferentData =
		"""
		title: Completely different feature
		type: enhancement
		products:
		  - product: kibana
		    target: 9.2.0
		prs:
		- "999"
		""";

	[Fact]
	public async Task ValidateBundle_FileUnchanged_NoWarning()
	{
		// Arrange — bundle stores checksum, file on disk is unchanged
		var (bundleFile, changelogDir) = await SetupBundleWithFileAsync(
			ChangelogWithoutComments,
			storedChecksum: ComputeSha1(ChangelogWithoutComments)
		);

		var input = CreateRenderInput(bundleFile, changelogDir);

		// Act
		var result = await Service.RenderChangelogs(Collector, input, TestContext.Current.CancellationToken);

		// Assert
		result.Should().BeTrue();
		Collector.Warnings.Should().Be(0, "no checksum mismatch expected when file is unchanged");
	}

	[Fact]
	public async Task ValidateBundle_CommentsChangedButDataUnchanged_NoWarning()
	{
		// Arrange — bundle stores checksum from commented file,
		// but file on disk now has comments removed.
		// ComputeSha1 normalizes (strips comments), so the checksum still matches.
		var (bundleFile, changelogDir) = await SetupBundleWithFileAsync(
			fileOnDisk: ChangelogWithoutComments,
			storedChecksum: ComputeSha1(ChangelogWithComments)
		);

		var input = CreateRenderInput(bundleFile, changelogDir);

		// Act
		var result = await Service.RenderChangelogs(Collector, input, TestContext.Current.CancellationToken);

		// Assert
		result.Should().BeTrue();
		Collector.Warnings.Should().Be(0,
			"checksum should match regardless of comment changes");
	}

	[Fact]
	public async Task ValidateBundle_FileDataChanged_EmitsWarning()
	{
		// Arrange — bundle stores checksum of one file, but file on disk has different data
		var (bundleFile, changelogDir) = await SetupBundleWithFileAsync(
			fileOnDisk: ChangelogWithDifferentData,
			storedChecksum: ComputeSha1(ChangelogWithoutComments)
		);

		var input = CreateRenderInput(bundleFile, changelogDir);

		// Act
		var result = await Service.RenderChangelogs(Collector, input, TestContext.Current.CancellationToken);

		// Assert
		result.Should().BeTrue("warnings don't prevent rendering");
		Collector.Warnings.Should().BeGreaterThan(0);
		Collector.Diagnostics.Should().Contain(d =>
			d.Severity == Severity.Warning &&
			d.Message.Contains("Checksum mismatch") &&
			d.Message.Contains("the file content has changed since it was bundled") &&
			d.Message.Contains("re-run 'bundle' or 'bundle-amend'") &&
			d.Message.Contains("--resolve"));
	}

	[Fact]
	public async Task ValidateBundle_ResolvedEntry_SkipsChecksumValidation()
	{
		// Arrange — resolved entry has inline data, no file reference needed
		var bundleDir = FileSystem.Path.Combine(FileSystem.Path.GetTempPath(), Guid.NewGuid().ToString());
		FileSystem.Directory.CreateDirectory(bundleDir);

		var bundleFile = FileSystem.Path.Combine(bundleDir, "bundle.yaml");
		// language=yaml
		var bundleContent =
			"""
			products:
			  - product: elasticsearch
			    target: 9.2.0
			entries:
			  - type: feature
			    title: Resolved feature
			    products:
			      - product: elasticsearch
			        target: 9.2.0
			    prs:
			    - "100"
			""";
		await FileSystem.File.WriteAllTextAsync(bundleFile, bundleContent, TestContext.Current.CancellationToken);

		var input = CreateRenderInput(bundleFile, bundleDir);

		// Act
		var result = await Service.RenderChangelogs(Collector, input, TestContext.Current.CancellationToken);

		// Assert
		result.Should().BeTrue();
		Collector.Warnings.Should().Be(0, "resolved entries bypass file checksum validation");
	}

	[Fact]
	public void Checksums_WithAndWithoutComments_AreEqual()
	{
		// Verify that checksums ignore comment lines (normalization strips them)
		var withComments = ComputeSha1(ChangelogWithComments);
		var withoutComments = ComputeSha1(ChangelogWithoutComments);

		withComments.Should().Be(withoutComments,
			"checksum should be identical regardless of comment lines");
	}

	private async Task<(string BundleFile, string ChangelogDir)> SetupBundleWithFileAsync(
		string fileOnDisk,
		string storedChecksum)
	{
		var changelogDir = FileSystem.Path.Combine(FileSystem.Path.GetTempPath(), Guid.NewGuid().ToString());
		FileSystem.Directory.CreateDirectory(changelogDir);

		var changelogFileName = "1755268130-feature.yaml";
		var changelogFile = FileSystem.Path.Combine(changelogDir, changelogFileName);
		await FileSystem.File.WriteAllTextAsync(changelogFile, fileOnDisk, TestContext.Current.CancellationToken);

		var bundleDir = FileSystem.Path.Combine(FileSystem.Path.GetTempPath(), Guid.NewGuid().ToString());
		FileSystem.Directory.CreateDirectory(bundleDir);

		var bundleFile = FileSystem.Path.Combine(bundleDir, "bundle.yaml");
		// language=yaml
		var bundleContent =
			$"""
			products:
			  - product: elasticsearch
			    target: 9.2.0
			entries:
			  - file:
			      name: {changelogFileName}
			      checksum: {storedChecksum}
			""";
		await FileSystem.File.WriteAllTextAsync(bundleFile, bundleContent, TestContext.Current.CancellationToken);

		return (bundleFile, changelogDir);
	}

	private RenderChangelogsArguments CreateRenderInput(string bundleFile, string changelogDir) =>
		new()
		{
			Bundles = [new BundleInput { BundleFile = bundleFile, Directory = changelogDir }],
			Output = FileSystem.Path.Combine(FileSystem.Path.GetTempPath(), Guid.NewGuid().ToString()),
			Title = "9.2.0"
		};
}
