// Licensed to Elasticsearch B.V under one or more agreements.
// Elasticsearch B.V licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information

using AwesomeAssertions;
using Elastic.Changelog.Rendering;
using Elastic.Documentation.Configuration;

namespace Elastic.Changelog.Tests.Changelogs.Render;

public class ChecksumValidationTests(ITestOutputHelper output) : RenderChangelogTestBase(output)
{
	// language=yaml
	private const string BundleHeader =
		"""
		products:
		  - product: elasticsearch
		    target: 9.2.0
		""";

	// language=yaml
	private const string ChangelogWithComments =
		"""
		# This is a generated changelog entry
		# Do not edit this file directly
		title: My new feature
		type: feature
		products:
		  - product: elasticsearch
		    target: 9.2.0
		prs:
		- "100"
		""";

	// language=yaml
	private const string ChangelogWithoutComments =
		"""
		title: My new feature
		type: feature
		products:
		  - product: elasticsearch
		    target: 9.2.0
		prs:
		- "100"
		""";

	[Fact]
	public async Task RenderChangelogs_ResolvedBundle_RendersWithoutReadingFiles()
	{
		// Arrange — bundles are self-contained: entries carry inline content and the
		// file block is provenance only, so no changelog file exists on disk
		var bundleDir = FileSystem.Path.Join(Paths.WorkingDirectoryRoot.FullName, Guid.NewGuid().ToString());
		FileSystem.Directory.CreateDirectory(bundleDir);

		var bundleFile = FileSystem.Path.Join(bundleDir, "bundle.yaml");
		var bundleContent = CreateResolvedBundleContent(BundleHeader, ("1755268130-feature.yaml", ChangelogWithoutComments));
		await FileSystem.File.WriteAllTextAsync(bundleFile, bundleContent, TestContext.Current.CancellationToken);

		var outputDir = FileSystem.Path.Join(Paths.WorkingDirectoryRoot.FullName, Guid.NewGuid().ToString());
		var input = new RenderChangelogsArguments
		{
			Bundles = [new BundleInput { BundleFile = bundleFile }],
			Output = outputDir,
			Title = "9.2.0"
		};

		// Act
		var result = await Service.RenderChangelogs(Collector, input, TestContext.Current.CancellationToken);

		// Assert
		result.Should().BeTrue();
		Collector.Errors.Should().Be(0);
		Collector.Warnings.Should().Be(0, "rendering never reads changelog files, so provenance checksums are not verified");

		var indexFile = FileSystem.Path.Join(outputDir, "9.2.0", "index.md");
		FileSystem.File.Exists(indexFile).Should().BeTrue();
		var indexContent = await FileSystem.File.ReadAllTextAsync(indexFile, TestContext.Current.CancellationToken);
		indexContent.Should().Contain("My new feature");
	}

	[Fact]
	public void Checksums_WithAndWithoutComments_AreEqual()
	{
		// Verify that checksums ignore comment lines (normalization strips them)
		var withComments = ComputeSha1(ChangelogWithComments);
		var withoutComments = ComputeSha1(ChangelogWithoutComments);

		withComments.Should().Be(withoutComments,
			"checksum should be identical regardless of comment lines");
	}
}
