// Licensed to Elasticsearch B.V under one or more agreements.
// Elasticsearch B.V licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information

module ``AuthoringTests``.``documentation generator``.``links json artifact``

open Xunit
open authoring

type ``two pages with anchors end up in artifact`` () =

    static let generator = Setup.Generate [
        Index """
# A Document that lives at the root

*Welcome* to this documentation

## This anchor is autogenerated

### Several pages can be created [#and-anchored]

Through various means $$$including-this-inline-syntax$$$
"""
        Markdown "file.md" "*hello* world"
    ]

    [<Fact>]
    let ``validate index.md HTML`` () =
        generator |> converts "index.md" |> toHtml """
             <p>
 	            <em>Welcome</em>
 	            to this documentation</p>
             <div class="heading-wrapper">
                 <h2 id="this-anchor-is-autogenerated">
 		            <a class="headerlink" href="#this-anchor-is-autogenerated">This anchor is autogenerated</a>
 	            </h2>
             </div>
             <div class="heading-wrapper">
                 <h3 id="and-anchored">
 		            <a class="headerlink" href="#and-anchored">Several pages can be created</a>
 	            </h3>
             </div>
             <p>Through various means
 	            <a id="including-this-inline-syntax"></a>
             </p>
        """

    [<Fact>]
    let ``validate file.md HTML`` () =
        generator |> converts "file.md" |> toHtml "<p><em>hello</em>world</p>"

    [<Fact>]
    let ``has no errors`` () = generator |> hasNoErrors

    [<Fact>]
    let ``validate links.json`` () =
        generator |> convertsToJson ".artifacts/docs/html/links.json" """{
         "origin": {
           "branch": "unavailable",
           "remote": "unavailable",
           "ref": "unavailable",
           "name": "unavailable",
           "github_ref": null
         },
         "url_path_prefix": "",
         "links": {
           "cli/changelog/index.md": {},
           "cli/installation.md": {},
           "file.md": {},
           "index.md": {
             "anchors": [
               "including-this-inline-syntax",
              "this-anchor-is-autogenerated",
              "and-anchored"
            ]
           },
           "schema-support/api-explorer/index.md": {},
           "schema-support/cli-schema/index.md": {},
           "schema-support/cli-schema/supplemental.md": {},
           "testing/redirects/5th-page.md": {
             "anchors": [ "bb" ]
           },
           "testing/redirects/first-page.md": {
             "anchors": [ "has-an-anchor-as-well" ]
           },
           "testing/redirects/second-page.md": {
             "anchors": [ "active-anchor", "zz", "yy" ]
           },
           "testing/redirects/third-page.md": {
             "anchors": [ "bb" ]
           }
         },
         "cross_links": [],
         "redirects": {
           "migration/freeze/gh-action.md": {
              "to": "index.md"
           },
           "migration/freeze/index.md": {
             "to": "index.md"
           },
           "cli/cli-reference-how-to.md": { "to": "schema-support/cli-schema/index.md" },
           "cli/cli-supplemental-docs.md": { "to": "schema-support/cli-schema/supplemental.md" },
           "configure/content-set/api-explorer.md": { "to": "schema-support/api-explorer/index.md" },
           "cli/index.md": { "to": "cli/installation.md" },
           "cli/assembler/index.md": { "to": "cli/installation.md" },
           "cli/changelog/add.md": { "to": "cli/changelog/index.md" },
           "cli/changelog/bundle-amend.md": { "to": "cli/changelog/index.md" },
           "cli/changelog/bundle.md": { "to": "cli/changelog/index.md" },
           "cli/changelog/evaluate-pr.md": { "to": "cli/changelog/index.md" },
           "cli/changelog/gh-release.md": { "to": "cli/changelog/index.md" },
           "cli/changelog/init.md": { "to": "cli/changelog/index.md" },
           "cli/changelog/remove.md": { "to": "cli/changelog/index.md" },
           "cli/changelog/render.md": { "to": "cli/changelog/index.md" },
           "cli/assembler/assemble.md": { "to": "cli/installation.md" },
           "cli/assembler/assembler-bloom-filter-create.md": { "to": "cli/installation.md" },
           "cli/assembler/assembler-bloom-filter-lookup.md": { "to": "cli/installation.md" },
           "cli/assembler/assembler-build.md": { "to": "cli/installation.md" },
           "cli/assembler/assembler-clone.md": { "to": "cli/installation.md" },
           "cli/assembler/assembler-config-init.md": { "to": "cli/installation.md" },
           "cli/assembler/assembler-content-source-match.md": { "to": "cli/installation.md" },
           "cli/assembler/assembler-content-source-validate.md": { "to": "cli/installation.md" },
           "cli/assembler/assembler-deploy-apply.md": { "to": "cli/installation.md" },
           "cli/assembler/assembler-deploy-plan.md": { "to": "cli/installation.md" },
           "cli/assembler/assembler-deploy-update-redirects.md": { "to": "cli/installation.md" },
           "cli/assembler/assembler-index.md": { "to": "cli/installation.md" },
           "cli/assembler/assembler-navigation-validate-link-reference.md": { "to": "cli/installation.md" },
           "cli/assembler/assembler-navigation-validate.md": { "to": "cli/installation.md" },
           "cli/assembler/assembler-serve.md": { "to": "cli/installation.md" },
           "cli/docset/index.md": { "to": "cli/installation.md" },
           "cli/docset/build.md": { "to": "cli/installation.md" },
           "cli/docset/diff-validate.md": { "to": "cli/installation.md" },
           "cli/docset/format.md": { "to": "cli/installation.md" },
           "cli/docset/index-command.md": { "to": "cli/installation.md" },
           "cli/docset/mv.md": { "to": "cli/installation.md" },
           "cli/docset/serve.md": { "to": "cli/installation.md" },
           "cli/links/index.md": { "to": "cli/installation.md" },
           "cli/links/inbound-links-validate.md": { "to": "cli/installation.md" },
           "cli/links/inbound-links-validate-all.md": { "to": "cli/installation.md" },
           "cli/links/inbound-links-validate-link-reference.md": { "to": "cli/installation.md" },
           "testing/redirects/4th-page.md": {
             "to": "testing/redirects/5th-page.md"
           },
           "testing/redirects/9th-page.md": {
             "anchors": { "!": "!" },
             "to": "testing/redirects/5th-page.md"
           },
           "testing/redirects/6th-page.md": {
             "anchors": { "!": "!" },
             "to": "index.md"
           },
           "testing/redirects/7th-page.md": {
             "anchors": { "!": "!" },
             "to": "testing/redirects/5th-page.md"
           },
           "testing/redirects/first-page-old.md": {
             "anchors": {
               "old-anchor": "active-anchor",
               "removed-anchor": null
             },
             "to": "testing/redirects/second-page.md"
           },
           "testing/redirects/second-page-old.md": {
             "many": [
               {
                 "anchors": { "aa": "zz", "removed-anchor": null },
                 "to": "testing/redirects/second-page.md"
               },
               {
                 "anchors": { "yy": "bb" },
                 "to": "testing/redirects/third-page.md"
               }
             ]
           },
           "testing/redirects/third-page.md": {
             "anchors": { "removed-anchor": null },
             "to": "testing/redirects/third-page.md"
           }
         }
       }
       """
