// Licensed to Elasticsearch B.V under one or more agreements.
// Elasticsearch B.V licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information

module ``AuthoringTests``.``documentation generator``.``links json artifact``

open Xunit
open authoring

type ``two pages with anchors end up in artifact`` () =

    static let generator = Setup.Generate [
        Index """
# A Document that lives at the root

*Welcome* to this documentation

## This anchor is autogenerated

### Several pages can be created [#and-anchored]

Through various means $$$including-this-inline-syntax$$$
"""
        Markdown "file.md" "*hello* world"
    ]

    [<Fact>]
    let ``validate index.md HTML`` () =
        generator |> converts "index.md" |> toHtml """
             <p>
 	            <em>Welcome</em>
 	            to this documentation</p>
             <div class="heading-wrapper" id="this-anchor-is-autogenerated">
                 <h2>
 		            <a class="headerlink" href="#this-anchor-is-autogenerated">This anchor is autogenerated</a>
 	            </h2>
             </div>
             <div class="heading-wrapper" id="and-anchored">
                 <h3>
 		            <a class="headerlink" href="#and-anchored">Several pages can be created</a>
 	            </h3>
             </div>
             <p>Through various means
 	            <a id="including-this-inline-syntax"></a>
             </p>
        """

    [<Fact>]
    let ``validate file.md HTML`` () =
        generator |> converts "file.md" |> toHtml "<p><em>hello</em>world</p>"

    [<Fact>]
    let ``has no errors`` () = generator |> hasNoErrors

    [<Fact>]
    let ``validate links.json`` () =
        generator |> convertsToJson ".artifacts/docs/html/links.json" """{
  "origin": {
    "branch": "unavailable",
    "remote": "unavailable",
    "ref": "unavailable",
    "name": "unavailable",
    "github_ref": null
  },
  "url_path_prefix": "",
  "links": {
    "cli/changelog/index.md": {},
    "data/cli-schema/index.md": {},
    "data/cli-schema/supplemental.md": {},
    "data/index.md": {},
    "data/mcp/index.md": {},
    "data/openapi/api-explorer.md": {},
    "data/release-notes/bundle.md": {},
    "data/release-notes/configure-ref.md": {},
    "data/release-notes/configure.md": {},
    "data/release-notes/create.md": {},
    "data/release-notes/overview.md": {},
    "data/release-notes/publish.md": {},
    "development/ingest.md": {},
    "development/navigation.md": {},
    "documentation/assembler/add-repo.md": {},
    "documentation/assembler/configure/index.md": {},
    "documentation/assembler/environments.md": {},
    "documentation/assembler/index.md": {},
    "documentation/assembler/navigation.md": {},
    "documentation/catalog/legacy-url-mappings.md": {},
    "documentation/catalog/products.md": {},
    "documentation/catalog/synonyms.md": {},
    "documentation/catalog/versions.md": {},
    "documentation/cross-links.md": {},
    "documentation/distributed-builds.md": {},
    "documentation/isolated/configure/index.md": {},
    "documentation/isolated/cta.md": {},
    "documentation/isolated/extensions.md": {},
    "documentation/isolated/how-to/cumulative-docs/badge-placement.md": {},
    "documentation/isolated/how-to/cumulative-docs/example-scenarios.md": {},
    "documentation/isolated/how-to/cumulative-docs/guidelines.md": {},
    "documentation/isolated/how-to/cumulative-docs/index.md": {},
    "documentation/isolated/how-to/cumulative-docs/reference.md": {},
    "documentation/isolated/how-to/locally.md": {},
    "documentation/isolated/how-to/move.md": {},
    "documentation/isolated/how-to/on-the-web.md": {},
    "documentation/isolated/index.md": {},
    "documentation/isolated/navigation.md": {},
    "documentation/isolated/urls.md": {},
    "documentation/redirects.md": {},
    "file.md": {},
    "getting-started/installation.md": {},
    "index.md": {
      "anchors": [
        "including-this-inline-syntax",
        "this-anchor-is-autogenerated",
        "and-anchored"
      ]
    },
    "syntax/file_inclusion.md": {},
    "syntax/index.md": {},
    "testing/redirects/5th-page.md": {
      "anchors": [
        "bb"
      ]
    },
    "testing/redirects/first-page.md": {
      "anchors": [
        "has-an-anchor-as-well"
      ]
    },
    "testing/redirects/second-page.md": {
      "anchors": [
        "active-anchor",
        "zz",
        "yy"
      ]
    },
    "testing/redirects/third-page.md": {
      "anchors": [
        "bb"
      ]
    }
  },
  "cross_links": [],
  "redirects": {
    "migration/freeze/gh-action.md": {
      "to": "index.md"
    },
    "migration/freeze/index.md": {
      "to": "index.md"
    },
    "migration/index.md": {
      "to": "index.md"
    },
    "migration/syntax.md": {
      "to": "syntax/index.md"
    },
    "migration/ia.md": {
      "to": "index.md"
    },
    "migration/versioning.md": {
      "to": "index.md"
    },
    "migration/engineering.md": {
      "to": "index.md"
    },
    "migration/guide/index.md": {
      "to": "index.md"
    },
    "migration/guide/working-in-docs-content.md": {
      "to": "index.md"
    },
    "migration/guide/automated.md": {
      "to": "index.md"
    },
    "migration/guide/tooling.md": {
      "to": "index.md"
    },
    "migration/guide/move-ref-docs.md": {
      "to": "index.md"
    },
    "migration/guide/mapping.md": {
      "to": "index.md"
    },
    "migration/guide/how-to-set-up-docs-previews.md": {
      "to": "index.md"
    },
    "syntax/conditionals.md": {
      "to": "syntax/index.md"
    },
    "syntax/example_blocks.md": {
      "to": "syntax/index.md"
    },
    "syntax/passthrough.md": {
      "to": "syntax/index.md"
    },
    "syntax/sidebars.md": {
      "to": "syntax/index.md"
    },
    "syntax/tagged_regions.md": {
      "to": "syntax/file_inclusion.md"
    },
    "building-blocks/index.md": {
      "to": "documentation/distributed-builds.md"
    },
    "building-blocks/documentation-set.md": {
      "to": "documentation/isolated/configure/index.md"
    },
    "building-blocks/assembled-documentation.md": {
      "to": "documentation/assembler/index.md"
    },
    "building-blocks/distributed-documentation.md": {
      "to": "documentation/distributed-builds.md"
    },
    "building-blocks/link-service.md": {
      "to": "documentation/distributed-builds.md"
    },
    "building-blocks/link-index.md": {
      "to": "documentation/distributed-builds.md"
    },
    "building-blocks/link-catalog.md": {
      "to": "documentation/distributed-builds.md"
    },
    "building-blocks/outbound-cross-links.md": {
      "to": "documentation/cross-links.md"
    },
    "building-blocks/inbound-cross-links.md": {
      "to": "documentation/cross-links.md"
    },
    "building-blocks/documentation-set-navigation.md": {
      "to": "documentation/isolated/navigation.md"
    },
    "building-blocks/global-navigation.md": {
      "to": "documentation/assembler/navigation.md"
    },
    "configure/index.md": {
      "to": "documentation/isolated/configure/index.md"
    },
    "configure/page.md": {
      "to": "documentation/isolated/configure/index.md"
    },
    "configure/content-sources.md": {
      "to": "documentation/assembler/environments.md"
    },
    "configure/site/index.md": {
      "to": "documentation/assembler/configure/index.md"
    },
    "configure/site/content.md": {
      "to": "documentation/assembler/configure/index.md"
    },
    "configure/site/navigation.md": {
      "to": "documentation/assembler/navigation.md"
    },
    "configure/site/products.md": {
      "to": "documentation/catalog/products.md"
    },
    "configure/site/versions.md": {
      "to": "documentation/catalog/versions.md"
    },
    "configure/site/legacy-url-mappings.md": {
      "to": "documentation/catalog/legacy-url-mappings.md"
    },
    "configure/site/synonyms.md": {
      "to": "documentation/catalog/synonyms.md"
    },
    "configure/content-set/index.md": {
      "to": "documentation/isolated/configure/index.md"
    },
    "configure/content-set/navigation.md": {
      "to": "documentation/isolated/configure/index.md"
    },
    "configure/content-set/attributes.md": {
      "to": "documentation/isolated/configure/index.md"
    },
    "configure/content-set/file-structure.md": {
      "to": "documentation/isolated/urls.md"
    },
    "configure/content-set/extensions.md": {
      "to": "documentation/isolated/extensions.md"
    },
    "configure/content-set/cta.md": {
      "to": "documentation/isolated/cta.md"
    },
    "configure/content-set/api-explorer.md": {
      "to": "data/openapi/api-explorer.md"
    },
    "contribute/index.md": {
      "to": "documentation/isolated/index.md"
    },
    "contribute/move.md": {
      "to": "documentation/isolated/how-to/move.md"
    },
    "contribute/redirects.md": {
      "to": "documentation/redirects.md"
    },
    "contribute/branching-strategy.md": {
      "to": "documentation/assembler/environments.md"
    },
    "contribute/add-repo.md": {
      "to": "documentation/assembler/add-repo.md"
    },
    "contribute/release-new-version.md": {
      "to": "documentation/assembler/environments.md"
    },
    "contribute/locally.md": {
      "to": "documentation/isolated/how-to/locally.md"
    },
    "contribute/on-the-web.md": {
      "to": "documentation/isolated/how-to/on-the-web.md"
    },
    "contribute/cumulative-docs/index.md": {
      "to": "documentation/isolated/how-to/cumulative-docs/index.md"
    },
    "contribute/cumulative-docs/guidelines.md": {
      "to": "documentation/isolated/how-to/cumulative-docs/guidelines.md"
    },
    "contribute/cumulative-docs/badge-placement.md": {
      "to": "documentation/isolated/how-to/cumulative-docs/badge-placement.md"
    },
    "contribute/cumulative-docs/example-scenarios.md": {
      "to": "documentation/isolated/how-to/cumulative-docs/example-scenarios.md"
    },
    "contribute/cumulative-docs/reference.md": {
      "to": "documentation/isolated/how-to/cumulative-docs/reference.md"
    },
    "contribute/changelog.md": {
      "to": "data/release-notes/overview.md"
    },
    "contribute/configure-changelogs.md": {
      "to": "data/release-notes/configure.md"
    },
    "contribute/configure-changelogs-ref.md": {
      "to": "data/release-notes/configure-ref.md"
    },
    "contribute/create-changelogs.md": {
      "to": "data/release-notes/create.md"
    },
    "contribute/bundle-changelogs.md": {
      "to": "data/release-notes/bundle.md"
    },
    "contribute/publish-changelogs.md": {
      "to": "data/release-notes/publish.md"
    },
    "schema-support/index.md": {
      "to": "data/index.md"
    },
    "schema-support/api-explorer/index.md": {
      "to": "data/openapi/api-explorer.md"
    },
    "schema-support/cli-schema/index.md": {
      "to": "data/cli-schema/index.md"
    },
    "schema-support/cli-schema/supplemental.md": {
      "to": "data/cli-schema/supplemental.md"
    },
    "mcp/index.md": {
      "to": "data/mcp/index.md"
    },
    "cli/installation.md": {
      "to": "getting-started/installation.md"
    },
    "cli/shell-autocompletion.md": {
      "to": "getting-started/installation.md"
    },
    "cli/cli-reference-how-to.md": {
      "to": "data/cli-schema/index.md"
    },
    "cli/cli-supplemental-docs.md": {
      "to": "data/cli-schema/supplemental.md"
    },
    "cli/index.md": {
      "to": "getting-started/installation.md"
    },
    "cli/assembler/index.md": {
      "to": "getting-started/installation.md"
    },
    "cli/changelog/add.md": {
      "to": "cli/changelog/index.md"
    },
    "cli/changelog/bundle-amend.md": {
      "to": "cli/changelog/index.md"
    },
    "cli/changelog/bundle.md": {
      "to": "cli/changelog/index.md"
    },
    "cli/changelog/evaluate-pr.md": {
      "to": "cli/changelog/index.md"
    },
    "cli/changelog/gh-release.md": {
      "to": "cli/changelog/index.md"
    },
    "cli/changelog/init.md": {
      "to": "cli/changelog/index.md"
    },
    "cli/changelog/remove.md": {
      "to": "cli/changelog/index.md"
    },
    "cli/changelog/render.md": {
      "to": "cli/changelog/index.md"
    },
    "cli/assembler/assemble.md": {
      "to": "getting-started/installation.md"
    },
    "cli/assembler/assembler-bloom-filter-create.md": {
      "to": "getting-started/installation.md"
    },
    "cli/assembler/assembler-bloom-filter-lookup.md": {
      "to": "getting-started/installation.md"
    },
    "cli/assembler/assembler-build.md": {
      "to": "getting-started/installation.md"
    },
    "cli/assembler/assembler-clone.md": {
      "to": "getting-started/installation.md"
    },
    "cli/assembler/assembler-config-init.md": {
      "to": "getting-started/installation.md"
    },
    "cli/assembler/assembler-content-source-match.md": {
      "to": "getting-started/installation.md"
    },
    "cli/assembler/assembler-content-source-validate.md": {
      "to": "getting-started/installation.md"
    },
    "cli/assembler/assembler-deploy-apply.md": {
      "to": "getting-started/installation.md"
    },
    "cli/assembler/assembler-deploy-plan.md": {
      "to": "getting-started/installation.md"
    },
    "cli/assembler/assembler-deploy-update-redirects.md": {
      "to": "getting-started/installation.md"
    },
    "cli/assembler/assembler-index.md": {
      "to": "getting-started/installation.md"
    },
    "cli/assembler/assembler-navigation-validate-link-reference.md": {
      "to": "getting-started/installation.md"
    },
    "cli/assembler/assembler-navigation-validate.md": {
      "to": "getting-started/installation.md"
    },
    "cli/assembler/assembler-serve.md": {
      "to": "getting-started/installation.md"
    },
    "cli/docset/index.md": {
      "to": "getting-started/installation.md"
    },
    "cli/docset/build.md": {
      "to": "getting-started/installation.md"
    },
    "cli/docset/diff-validate.md": {
      "to": "getting-started/installation.md"
    },
    "cli/docset/format.md": {
      "to": "getting-started/installation.md"
    },
    "cli/docset/index-command.md": {
      "to": "getting-started/installation.md"
    },
    "cli/docset/mv.md": {
      "to": "getting-started/installation.md"
    },
    "cli/docset/serve.md": {
      "to": "getting-started/installation.md"
    },
    "cli/links/index.md": {
      "to": "getting-started/installation.md"
    },
    "cli/links/inbound-links-validate.md": {
      "to": "getting-started/installation.md"
    },
    "cli/links/inbound-links-validate-all.md": {
      "to": "getting-started/installation.md"
    },
    "cli/links/inbound-links-validate-link-reference.md": {
      "to": "getting-started/installation.md"
    },
    "development/ingest/index.md": {
      "to": "development/ingest.md"
    },
    "development/link-validation/link-validation.md": {
      "to": "documentation/cross-links.md"
    },
    "development/navigation/navigation.md": {
      "to": "development/navigation.md"
    },
    "development/navigation/visual-walkthrough.md": {
      "to": "development/navigation.md"
    },
    "development/navigation/first-principles.md": {
      "to": "development/navigation.md"
    },
    "development/navigation/functional-principles.md": {
      "to": "development/navigation.md"
    },
    "development/navigation/technical-principles.md": {
      "to": "development/navigation.md"
    },
    "development/navigation/two-phase-loading.md": {
      "to": "development/navigation.md"
    },
    "development/navigation/node-types.md": {
      "to": "development/navigation.md"
    },
    "development/navigation/home-provider-architecture.md": {
      "to": "development/navigation.md"
    },
    "development/navigation/assembler-process.md": {
      "to": "development/navigation.md"
    },
    "testing/index.md": {
      "to": "index.md"
    },
    "testing/archive.md": {
      "to": "index.md"
    },
    "testing/cross-links.md": {
      "to": "index.md"
    },
    "testing/custom-highlighters.md": {
      "to": "index.md"
    },
    "testing/kibana-settings-yaml-samples.md": {
      "to": "index.md"
    },
    "testing/landing-page.md": {
      "to": "index.md"
    },
    "testing/req.md": {
      "to": "index.md"
    },
    "testing/security-settings.md": {
      "to": "index.md"
    },
    "testing/nested/index.md": {
      "to": "index.md"
    },
    "testing/mover/first-page.md": {
      "to": "index.md"
    },
    "testing/mover/second-page.md": {
      "to": "index.md"
    },
    "testing/nest-under-index/index.md": {
      "to": "index.md"
    },
    "testing/nest-under-index/nested-page-1.md": {
      "to": "index.md"
    },
    "testing/nest-under-index/nested-page-2.md": {
      "to": "index.md"
    },
    "testing/deeply-nested/index.md": {
      "to": "index.md"
    },
    "testing/deeply-nested/foo.md": {
      "to": "index.md"
    },
    "testing/deeply-nested/bar.md": {
      "to": "index.md"
    },
    "testing/deeply-nested/baz/qux.md": {
      "to": "index.md"
    },
    "testing/redirects/first-page.md": {
      "to": "index.md"
    },
    "testing/redirects/second-page.md": {
      "to": "index.md"
    },
    "testing/redirects/5th-page.md": {
      "to": "index.md"
    },
    "testing/release-notes/index.md": {
      "to": "index.md"
    },
    "testing/release-notes/highlights.md": {
      "to": "index.md"
    },
    "testing/release-notes/breaking-changes.md": {
      "to": "index.md"
    },
    "testing/release-notes/deprecations.md": {
      "to": "index.md"
    },
    "testing/release-notes/known-issues.md": {
      "to": "index.md"
    },
    "testing/release-notes-all/index.md": {
      "to": "index.md"
    },
    "testing/redirects/4th-page.md": {
      "to": "testing/redirects/5th-page.md"
    },
    "testing/redirects/9th-page.md": {
      "anchors": {
        "!": "!"
      },
      "to": "testing/redirects/5th-page.md"
    },
    "testing/redirects/6th-page.md": {
      "anchors": {
        "!": "!"
      },
      "to": "index.md"
    },
    "testing/redirects/7th-page.md": {
      "anchors": {
        "!": "!"
      },
      "to": "testing/redirects/5th-page.md"
    },
    "testing/redirects/first-page-old.md": {
      "anchors": {
        "old-anchor": "active-anchor",
        "removed-anchor": null
      },
      "to": "testing/redirects/second-page.md"
    },
    "testing/redirects/second-page-old.md": {
      "many": [
        {
          "anchors": {
            "aa": "zz",
            "removed-anchor": null
          },
          "to": "testing/redirects/second-page.md"
        },
        {
          "anchors": {
            "yy": "bb"
          },
          "to": "testing/redirects/third-page.md"
        }
      ]
    },
    "testing/redirects/third-page.md": {
      "anchors": {
        "removed-anchor": null
      },
      "to": "testing/redirects/third-page.md"
    }
  }
}"""
