// Licensed to Elasticsearch B.V under one or more agreements.
// Elasticsearch B.V licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information

module ``AuthoringTests``.``documentation generator``.``links json artifact``

open Xunit
open authoring

type ``two pages with anchors end up in artifact`` () =

    static let generator = Setup.Generate [
        Index """
# A Document that lives at the root

*Welcome* to this documentation

## This anchor is autogenerated

### Several pages can be created [#and-anchored]

Through various means $$$including-this-inline-syntax$$$
"""
        Markdown "file.md" "*hello* world"
    ]

    [<Fact>]
    let ``validate index.md HTML`` () =
        generator |> converts "index.md" |> toHtml """
             <p>
 	            <em>Welcome</em>
 	            to this documentation</p>
             <div class="heading-wrapper" id="this-anchor-is-autogenerated">
 	            <h2>
 		            <a class="headerlink" href="#this-anchor-is-autogenerated">This anchor is autogenerated</a>
 	            </h2>
             </div>
             <div class="heading-wrapper" id="and-anchored">
 	            <h3>
 		            <a class="headerlink" href="#and-anchored">Several pages can be created</a>
 	            </h3>
             </div>
             <p>Through various means
 	            <a id="including-this-inline-syntax"></a>
             </p>
        """

    [<Fact>]
    let ``validate file.md HTML`` () =
        generator |> converts "file.md" |> toHtml "<p><em>hello</em>world</p>"

    [<Fact>]
    let ``has no errors`` () = generator |> hasNoErrors

    [<Fact>]
    let ``validate links.json`` () =
        generator |> convertsToJson ".artifacts/docs/html/links.json" """{
         "origin": {
           "branch": "unavailable",
           "remote": "unavailable",
           "ref": "unavailable",
           "name": "unavailable",
           "github_ref": null
         },
         "url_path_prefix": "",
         "links": {
           "cli/changelog/add.md": {},
           "cli/changelog/bundle-amend.md": {},
           "cli/changelog/bundle.md": {},
           "cli/changelog/evaluate-pr.md": {},
           "cli/changelog/gh-release.md": {},
           "cli/changelog/index.md": {},
           "cli/changelog/init.md": {},
           "cli/changelog/remove.md": {},
           "cli/changelog/render.md": {},
           "file.md": {},
           "index.md": {
             "anchors": [
               "including-this-inline-syntax",
              "this-anchor-is-autogenerated",
              "and-anchored"
            ]
           },
           "testing/redirects/5th-page.md": {
             "anchors": [ "bb" ]
           },
           "testing/redirects/first-page.md": {
             "anchors": [ "has-an-anchor-as-well" ]
           },
           "testing/redirects/second-page.md": {
             "anchors": [ "active-anchor", "zz", "yy" ]
           },
           "testing/redirects/third-page.md": {
             "anchors": [ "bb" ]
           }
         },
         "cross_links": [],
         "redirects": {
           "migration/freeze/gh-action.md": {
              "to": "index.md"
           },
           "migration/freeze/index.md": {
             "to": "index.md"
           },
           "cli/mcp.md": {
             "to": "index.md"
           },
           "cli/release/changelog-add.md": {
             "to": "cli/changelog/add.md"
           },
           "cli/release/changelog-evaluate-artifact.md": {
             "to": "index.md"
           },
           "cli/release/changelog-evaluate-pr.md": {
             "to": "cli/changelog/evaluate-pr.md"
           },
           "cli/release/changelog-bundle.md": {
             "to": "cli/changelog/bundle.md"
           },
           "cli/release/changelog-bundle-amend.md": {
             "to": "cli/changelog/bundle-amend.md"
           },
           "cli/release/changelog-gh-release.md": {
             "to": "cli/changelog/gh-release.md"
           },
           "cli/release/changelog-init.md": {
             "to": "cli/changelog/init.md"
           },
           "cli/release/changelog-prepare-artifact.md": {
             "to": "index.md"
           },
           "cli/release/changelog-remove.md": {
             "to": "cli/changelog/remove.md"
           },
           "cli/release/changelog-render.md": {
             "to": "cli/changelog/render.md"
           },
           "cli/release/index.md": {
             "to": "cli/changelog/index.md"
           },
           "testing/redirects/4th-page.md": {
             "to": "testing/redirects/5th-page.md"
           },
           "testing/redirects/9th-page.md": {
             "anchors": { "!": "!" },
             "to": "testing/redirects/5th-page.md"
           },
           "testing/redirects/6th-page.md": {
             "anchors": { "!": "!" },
             "to": "index.md"
           },
           "testing/redirects/7th-page.md": {
             "anchors": { "!": "!" },
             "to": "testing/redirects/5th-page.md"
           },
           "testing/redirects/first-page-old.md": {
             "anchors": {
               "old-anchor": "active-anchor",
               "removed-anchor": null
             },
             "to": "testing/redirects/second-page.md"
           },
           "testing/redirects/second-page-old.md": {
             "many": [
               {
                 "anchors": { "aa": "zz", "removed-anchor": null },
                 "to": "testing/redirects/second-page.md"
               },
               {
                 "anchors": { "yy": "bb" },
                 "to": "testing/redirects/third-page.md"
               }
             ]
           },
           "testing/redirects/third-page.md": {
             "anchors": { "removed-anchor": null },
             "to": "testing/redirects/third-page.md"
           }
         }
       }
       """
