name: 'Validate Inbound Links'
description: 'Validates all published cross links from all known repositories against local links.json'

runs:
  using: 'docker'
  image: "docker://ghcr.io/elastic/docs-builder:edge"
  args:
    - "inbound-links"
    - "validate-link-reference"
