name: 'Validate Inbound Links'
description: 'Validates all published cross links from all known repositories against local links.json'

inputs:
  command:
    description: 'The assembler command to run'
    required: false
    default: "link validate-inbound-local"

runs:
  using: 'docker'
  image: "docker://ghcr.io/elastic/docs-assembler:edge"
