version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - '**/*'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '08:00'
    labels:
      - chore
  - package-ecosystem: npm
    directories:
      - '**/*'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '08:00'
    labels:
      - chore
  - package-ecosystem: nuget
    directories:
      - '**/*'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '08:00'
    labels:
      - chore
