version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - '**/*'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '08:00'
    labels:
      - chore
  - package-ecosystem: npm
    directories:
      - '**/*'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '08:00'
    groups:
      tailwindcss:
        patterns:
          - 'tailwindcss'
          - '@tailwindcss/postcss'
          - 'prettier-plugin-tailwindcss'
    labels:
      - chore
  - package-ecosystem: nuget
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '08:00'
    groups: 
      system-io-abstractions:
        patterns:
          - 'System.IO.Abstractions'
          - 'System.IO.Abstractions.*'
    labels:
      - chore
