name: 'Documentation Builder'
description: 'Build and validate documentation in your repository'

branding:
  icon: 'filter'
  color: 'red'

inputs:
  prefix:
    description: 'Path prefix for all urls'
    required: false
  strict:
    description: 'Treat warnings as errors'
    required: false
outputs:
  skip:
    description: "hint from the documentation tool to skip the docs build for this PR"
  landing-page:
    description: "The relative url (with path-prefix) to the landing page of the documentation"

runs:
  using: 'docker'
  image: "docker://ghcr.io/elastic/docs-builder:edge"
