<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\services\Elastic.Documentation.Integrations\Elastic.Documentation.Integrations.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="FakeItEasy" />
	</ItemGroup>

</Project>
