name: 'Validate Global Path Prefixes'
description: 'Validates local path prefixes in local links.json against claimed prefixes in assemblers navigation.yml '

runs:
  using: 'docker'
  image: "docker://ghcr.io/elastic/docs-builder:edge"
  args:
    - "assembler"
    - "navigation"
    - "validate-link-reference"
