<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Elastic.Authoring.Tests</RootNamespace>
    <UseTUnit>true</UseTUnit>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="YamlDotNet" />
    <PackageReference Include="AngleSharp.Diffing" />
    <PackageReference Include="DiffPlex" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Elastic.Markdown\Elastic.Markdown.csproj" />
  </ItemGroup>
</Project>
