environments:
  prod:
    uri: https://www.elastic.co
    path_prefix: docs
    content_source: current # current | next
    allow_indexing: true
    google_tag_manager:
      enabled: true
      id: GTM-KNJMG2M
  staging:
    uri: https://staging-website.elastic.co
    path_prefix: docs
    content_source: next
    google_tag_manager:
      enabled: true
      id: GTM-KNJMG2M
      auth: nPocPUG0wiH68jsVeyRSxA
      preview: env-507
      cookies_win: x
  edge: 
    uri: https://d34ipnu52o64md.cloudfront.net
    path_prefix: docs
    content_source: edge
    google_tag_manager:
      enabled: false
    feature_flags:
      LAZY_LOAD_NAVIGATION: true
      SEARCH_OR_ASK_AI: true
  dev:
    uri: http://localhost:4000
    content_source: current
    path_prefix: docs

shared_configuration:
  stack: &stack
    current:  9.1
    next: main
    edge: main

  master: &master
    current: master
    next: master
    edge: master

###
# 'narrative' shares the same keys as keys in 'references' (<repository_config>)
# 'narrative' defines the docs-content repository
###
narrative:
  checkout_strategy: full

###
# 'references' defines a map of `elastic/<repository_name> * <repository_config>
# repository_config:
#   skip: bool
#   checkout_strategy: full | partial
#             # 'full' git clone --depth-1 --single-branch
#             # 'partial' --cone sparse-checkout of only the 'docs' folder with --filter=blob:none
#   current: <git_ref>
#   next: <git_ref>
###
references:

  # @elastic/ingest-docs
  apm-server:
  apm-agent-android:
  apm-agent-dotnet:
  apm-agent-go:
  apm-agent-ios:
  apm-agent-java:
  apm-agent-nodejs:
  apm-agent-php:
  apm-agent-python:
  apm-agent-ruby:
  apm-agent-rum-js:
  apm-aws-lambda:
  apm-k8s-attacher:
  ecs:
    current: 9.1 # releases do not always align with the Stack version
    next: main
  ecs-dotnet:
  ecs-logging-go-logrus:
  ecs-logging-go-zap:
  ecs-logging-go-zerolog:
  ecs-logging-java:
  ecs-logging-nodejs:
  ecs-logging-php:
  ecs-logging-python:
  ecs-logging-ruby:
  ecs-logging:
  elastic-otel-dotnet:
  elastic-otel-java:
  elastic-otel-node:
  elastic-otel-php:
  elastic-otel-python:
  elastic-serverless-forwarder:
  integration-docs:
    private: true
  integrations:
  logstash-docs-md:
  opentelemetry:

  #stack aligned using gated deploys
  beats: *stack
  logstash: *stack

  # @elastic/admin-docs
  cloud-on-k8s:
  cloud:
    current: master
    next: master
    edge: master
    private: true

  curator: *master
  ecctl: *master

  # @elastic/admin-docs and @elastic/developer-docs
  elasticsearch:

  # @elastic/admin-docs and @elastic/experience-docs
  kibana:

  # @elastic/developer-docs
  eland:
  elasticsearch-hadoop:
  elasticsearch-java:
  elasticsearch-js:
  elasticsearch-net:
  elasticsearch-php:
  elasticsearch-py:
  elasticsearch-rs:
  elasticsearch-ruby:
  go-elasticsearch:
  search-ui:

  # @elastic/experience-docs
  detection-rules:
    checkout_strategy: full

  # @elastic/docs-engineering
  docs-builder:
    current: 9.0
    next: main
    skip: true
    sparse_paths: ["docs", "config"]
