#############################################
# This file defines the legacy URL mappings for the documentation site.
# It maps current documentation pages to older versions to ensure users can find the content they need.
# Upon creation of version selection dropdowns, this data is combined with the current version of its product.
#############################################

stack: &stack [ '9.0+', '8.19', '8.18', '8.17', '8.16', '8.15', '8.14', '8.13', '8.12', '8.11', '8.10', '8.9', '8.8', '8.7', '8.6', '8.5', '8.4', '8.3', '8.2', '8.1', '8.0', '7.17' ]

mappings:
  en/apm/agent/android/:
    product: apm-agent-android
    legacyVersions: [ '1.2.0' , '0.x' ]
  en/apm/agent/dotnet/:
    product: apm-agent-dotnet
    legacyVersions: [ '1.33.0' ]
  en/apm/agent/go/:
    product: apm-agent-go
    legacyVersions: [ '2.7.1', '1.x', '0.5' ]
  en/apm/agent/java/:
    product: apm-agent-java
    legacyVersions: ['1.54.0', '0.7', '0.6']
  en/apm/agent/nodejs/:
    product: apm-agent-nodejs
    legacyVersions: [ '4.x', '3.x', '2.x', '1.x' ]
  en/apm/agent/php/:
    product: apm-agent-php
    legacyVersions: [ '1.15.1', '1.x' ]
  en/apm/agent/python/:
    product: apm-agent-python
    legacyVersions: [ '6.24.0', '5.x', '4.x', '3.x', '2.x', '1.x' ]
  en/apm/agent/ruby/:
    product: apm-agent-ruby
    legacyVersions: [ '4.8.0', '3.x', '2.x', '1.x' ]
  en/apm/agent/rum-js/:
    product: apm-agent-rum-js
    legacyVersions: [ '5.17.0', '4.x', '3.x', '2.x', '1.x', '0.x' ]
  en/apm/agent/swift/:
    product: apm-agent-ios
    legacyVersions: [ '1.2.1', '0.x' ]
  en/apm/attacher/:
    product: apm-k8s-attacher
    legacyVersions: [ '1.1.3' ]
  en/apm/lambda/:
    product: apm-aws-lambda
    legacyVersions: [ '1.5.8' ]
  en/beats/auditbeat/:
    product: auditbeat
    legacyVersions: *stack
  en/beats/devguide/:
    product: beats
    legacyVersions: *stack
  en/beats/filebeat/:
    product: filebeat
    legacyVersions: *stack
  en/beats/functionbeat/:
    product: beats
    legacyVersions: *stack
  en/beats/heartbeat/:
    product: heartbeat
    legacyVersions: *stack
  en/beats/journalbeat/:
    product: beats
    legacyVersions: *stack
  en/beats/libbeat/:
    product: beats
    legacyVersions: *stack
  en/beats/loggingplugin/:
    product: beats
    legacyVersions: *stack
  en/beats/metricbeat/:
    product: metricbeat
    legacyVersions: *stack
  en/beats/packetbeat/:
    product: packetbeat
    legacyVersions: *stack
  en/beats/topbeat/:
    product: beats
    legacyVersions: *stack
  en/beats/winlogbeat/:
    product: winlogbeat
    legacyVersions: *stack
  en/cloud-heroku/:
    product: cloud-hosted
    legacyVersions: []
  en/cloud-on-k8s/:
    product: cloud-kubernetes
    legacyVersions: [ '3.0+', '2.16', '2.15', '2.14', '2.13', '2.12', '2.11', '2.10', '2.9', '2.8', '2.7', '2.6', '2.5', '2.4', '2.3', '2.2', '2.1', '2.0', '1.9', '1.8', '1.7', '1.6', '1.5', '1.4', '1.3', '1.2', '1.1', '1.0' ]
  en/cloud/:
    product: cloud-hosted
    legacyVersions: []
  en/cloud-enterprise/:
    product: cloud-enterprise
    legacyVersions: [ '4.0', '3.8', '3.7', '3.6', '3.5', '3.4', '3.3', '3.2', '3.1', '3.0', '2.13', '2.12', '2.11', '2.10', '2.9', '2.8', '2.7', '2.6', '2.5', '2.4', '2.3', '2.2', '2.1', '2.0', '1.1', '1.0' ]
  en/ecctl/:
    product: cloud-control-ecctl
    legacyVersions: [ '1.14+', '1.13', '1.12', '1.11', '1.10', '1.9', '1.8', '1.7', '1.6', '1.5', '1.4', '1.3', '1.2', '1.1', '1.0' ]
  en/ecs-logging/:
    product: ecs-logging
    legacyVersions: []
  en/ecs-logging/dotnet/:
    product: ecs-dotnet
    legacyVersions: []
  en/ecs-logging/go-logrus/:
    product: ecs-logging-go-logrus
    legacyVersions: []
  en/ecs-logging/go-zap/:
    product: ecs-logging-go-zap
    legacyVersions: []
  en/ecs-logging/go-zerolog/:
    product: ecs-logging-go-zerolog
    legacyVersions: []
  en/ecs-logging/java/:
    product: ecs-logging-java
    legacyVersions: ['0.x']
  en/ecs-logging/nodejs/:
    product: ecs-logging-nodejs
    legacyVersions: []
  en/ecs-logging/overview/:
    product: ecs-logging
    legacyVersions: []
  en/ecs-logging/php/:
    product: ecs-logging-php
    legacyVersions: []
  en/ecs-logging/python/:
    product: ecs-logging-python
    legacyVersions: [ '2.2.0' ]
  en/ecs-logging/ruby/:
    product: ecs-logging-ruby
    legacyVersions: []
  en/ecs/:
    product: ecs
    legacyVersions: [ '9.0+', '8.18', '8.17', '8.16', '8.15', '8.14', '8.13', '8.12', '8.11', '8.10', '8.9', '8.8', '8.7', '8.6', '8.5', '8.4', '8.3', '8.2', '8.1', '8.0', '1.12', '1.11', '1.10', '1.9', '1.8', '1.7', '1.6', '1.5', '1.4', '1.3', '1.2', '1.1', '1.0' ]
  en/elastic-stack-glossary/:
    product: elastic-stack
    legacyVersions: []
  en/elastic-stack/:
    product: elastic-stack
    legacyVersions: *stack
  en/elasticsearch/client/curator/:
    product: curator
    legacyVersions: [ '8.0.21', '7.0', '6.0', '5.8', '5.7', '5.6', '5.5', '5.4', '5.3', '5.2', '5.1', '5.0', '4.3', '4.2', '4.1', '4.0', '3.5', '3.4', '3.3' ]
  en/elasticsearch/client/eland/:
    product: eland
    legacyVersions: []
  en/elasticsearch/client/go-api/:
    product: elasticsearch
    legacyVersions: *stack
  en/elasticsearch/client/java-api-client/:
    product: elasticsearch
    legacyVersions: *stack
  en/elasticsearch/client/javascript-api/:
    product: elasticsearch
    legacyVersions: *stack
  en/elasticsearch/client/net-api/:
    product: elasticsearch
    legacyVersions: *stack
  en/elasticsearch/client/php-api/:
    product: elasticsearch
    legacyVersions: *stack
  en/elasticsearch/client/python-api/:
    product: elasticsearch
    legacyVersions: *stack
  en/elasticsearch/client/ruby-api/:
    product: elasticsearch
    legacyVersions: *stack
  en/elasticsearch/client/rust-api/:
    product: elasticsearch
    legacyVersions: *stack
  en/elasticsearch/hadoop/:
    product: elasticsearch
    legacyVersions: *stack
  en/elasticsearch/painless/:
    product: elasticsearch
    legacyVersions: *stack
  en/elasticsearch/plugins/:
    product: elasticsearch
    legacyVersions: *stack
  en/elasticsearch/reference/:
    product: elasticsearch
    legacyVersions: *stack
  en/esf/:
    product: elastic-serverless-forwarder
    legacyVersions: ['1.20.1']
  en/fleet/:
    product: elastic-agent
    legacyVersions: *stack
  en/ingest-overview/:
    product: elasticsearch
    legacyVersions: []
  en/ingest/:
    product: elasticsearch
    legacyVersions: *stack
  en/integrations-developer/:
    product: integrations
    legacyVersions: []
  en/integrations/:
    product: integrations
    legacyVersions: []
  en/kibana/:
    product: kibana
    legacyVersions: *stack
  en/logstash-versioned-plugins/:
    product: logstash
    legacyVersions: []
  en/logstash/:
    product: logstash
    legacyVersions: *stack
  en/machine-learning/:
    product: elasticsearch
    legacyVersions: *stack
  en/observability/:
    product: observability
    legacyVersions: *stack
  en/reference-architectures/:
    product: elasticsearch
    legacyVersions: []
  en/search-ui/:
    product: search-ui
    legacyVersions: ['1.24.1', '1.24.0']
  en/security/:
    product: security
    legacyVersions: *stack
  en/serverless/:
    product: serverless
    legacyVersions: []
  en/starting-with-the-elasticsearch-platform-and-its-solutions/:
    product: elasticsearch
    legacyVersions: *stack
