links:
  apm-with-elastic:
    title: APM with Elastic
    url: https://www.elastic.co/training/apm-with-elastic
  elastic-agent:
    title: Elastic Agent
    url: https://www.elastic.co/training/elastic-agent
  index-basics:
    title: Index Basics
    url: https://www.elastic.co/training/index-basics
  data-types-and-mappings:
    title: Data types and mappings on-demand training
    url: https://www.elastic.co/training/data-types-and-mappings
  rag-foundation:
    title: RAG Foundation on-demand training
    url: https://www.elastic.co/training/rag-foundation
  rag-beyond-basics:
    title: Beyond RAG basics: Advanced strategies for AI applications blog
    url: https://www.elastic.co/blog/beyond-rag-basics
  rag-build-system:
    title: Building a RAG System With Gemma, Hugging Face & Elasticsearch blog
    url: https://www.elastic.co/search-labs/blog/building-a-rag-system-with-gemma-hugging-face-elasticsearch
  rag-build-agentic:
    title: Agentic RAG with LangChain & Elasticsearch blog
    url: https://www.elastic.co/search-labs/blog/rag-agent-tool-elasticsearch-langchain
  semantic-search-foundation:
    title: Semantic search foundation on-demand training
    url: https://www.elastic.co/training/semantic-search-foundation
  semantic-search-text-embedding:
    title: Semantic search text embedding on-demand training
    url: https://www.elastic.co/training/semantic-search-text-embedding
  logs-essentials:
    url: https://www.elastic.co/training/logs-essentials-getting-started
    title: Logs essentials getting started on-demand training
