<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(SolutionRoot)\src\Elastic.Markdown\Elastic.Markdown.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Testcontainers.Elasticsearch" />
  </ItemGroup>

</Project>
