<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <InvariantGlobalization>true</InvariantGlobalization>
    <PublishAot>true</PublishAot>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="svgs\*.svg" />
    <EmbeddedResource Include="svgs\tokens\*.svg" />
  </ItemGroup>

</Project>
