scm:
  enabled: true
  owner: elastic
  repositories: |
    docs-builder
    edot-cloud-forwarder-aws
    edot-cloud-forwarder-azure
    edot-cloud-forwarder-gcp
    elastic-otel-rum-js
  branch: main