// Licensed to Elasticsearch B.V under one or more agreements.
// Elasticsearch B.V licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information

namespace Elastic.Authoring.Tests.Inline.RelativeLinks;

public class TwoPagesWithAnchorsEndUpInArtifact : GeneratorTest
{
	protected override IReadOnlyCollection<TestFile> Files =>
		[
			Index(
				"""
			# A Document that lives at the root

			*Welcome* to this documentation

			## This anchor is autogenerated

			### Several pages can be created [#and-anchored]

			Through various means $$$including-this-inline-syntax$$$
			"""
			),
			Page(
				"deeply/nested/file.md",
				"""
			# file.md

			[link to root](../../index.md#and-anchored)

			[link to parent](../parent.md)

			[link to parent](../parent.md#some-header)

			[link to sibling](./file2.md)
			"""
			),
			Page("deeply/nested/file2.md", """
			# file2.md
			"""),
			Page(
				"deeply/parent.md",
				"""
			# parent.md

			## some header
			[link to root](../index.md)
			"""
			)
		];

	[Fact(DisplayName = "validate index.md HTML")]
	public async Task ValidateHtml() =>
		await Docs.Converts("deeply/nested/file.md").ToHtml(
			"""
		<p><a href="/#and-anchored">link to root</a></p>
		<p><a href="/deeply/parent">link to parent</a></p>
		<p><a href="/deeply/parent#some-header">link to parent</a></p>
		<p><a href="/deeply/nested/file2">link to sibling</a></p>
		"""
		);

	[Fact(DisplayName = "has no errors")]
	public async Task HasNoErrors() => await Docs.HasNoErrors();
}
