// Product display name lookup
// This maps product IDs (from the search index) to human-readable display names
// Source: config/products.yml

export const PRODUCT_DISPLAY_NAMES: Record<string, string> = {
    apm: 'APM',
    'apm-agent': 'APM Agent',
    'apm-agent-dotnet': 'APM .NET Agent',
    'apm-agent-go': 'APM Go Agent',
    'apm-agent-java': 'APM Java Agent',
    'apm-agent-node': 'APM Node.js Agent',
    'apm-agent-php': 'APM PHP Agent',
    'apm-agent-python': 'APM Python Agent',
    'apm-agent-ruby': 'APM Ruby Agent',
    'apm-agent-rum-js': 'APM RUM JavaScript Agent',
    'apm-k8s-attacher': 'APM Attacher for Kubernetes',
    'apm-aws-lambda': 'APM AWS Lambda extension',
    'apm-server': 'APM Server',
    auditbeat: 'Auditbeat',
    beats: 'Beats',
    'cloud-control-ecctl': 'Elastic Cloud Control',
    'cloud-enterprise': 'Elastic Cloud Enterprise',
    'cloud-hosted': 'Elastic Cloud Hosted',
    'cloud-kubernetes': 'Elastic Cloud on Kubernetes',
    'cloud-serverless': 'Elastic Cloud Serverless',
    'cloud-terraform': 'Elastic Cloud Terraform Provider',
    'terraform-google-edot-cf': 'Terraform Google EDOT CF',
    curator: 'Elasticsearch Curator',
    ecs: 'Elastic Common Schema (ECS)',
    'ecs-logging': 'ECS Logging',
    'ecs-dotnet': 'ECS Logging .NET',
    'ecs-logging-go-logrus': 'ECS Logging Go (Logrus)',
    'ecs-logging-go-zap': 'ECS Logging Go (Zap)',
    'ecs-logging-go-zerolog': 'ECS Logging Go (Zerolog)',
    'ecs-logging-java': 'ECS Logging Java',
    'ecs-logging-nodejs': 'ECS Logging Node.js',
    'ecs-logging-php': 'ECS Logging PHP',
    'ecs-logging-python': 'ECS Logging Python',
    'ecs-logging-ruby': 'ECS Logging Ruby',
    'edot-cf': 'EDOT Cloud Forwarder',
    'edot-sdk': 'Elastic Distribution of OpenTelemetry SDK',
    'edot-collector': 'Elastic Distribution of OpenTelemetry Collector',
    'edot-ios': 'Elastic Distribution of OpenTelemetry iOS',
    'edot-android': 'Elastic Distribution of OpenTelemetry Android',
    'edot-dotnet': 'Elastic Distribution of OpenTelemetry .NET',
    'edot-java': 'Elastic Distribution of OpenTelemetry Java',
    'edot-node': 'Elastic Distribution of OpenTelemetry Node',
    'edot-php': 'Elastic Distribution of OpenTelemetry PHP',
    'edot-python': 'Elastic Distribution of OpenTelemetry Python',
    'edot-cf-aws': 'EDOT Cloud Forwarder for AWS',
    'edot-cf-azure': 'EDOT Cloud Forwarder for Azure',
    'edot-cf-gcp': 'EDOT Cloud Forwarder for GCP',
    eland: 'Eland',
    'elastic-agent': 'Elastic Agent',
    'elastic-serverless-forwarder': 'Elastic Serverless Forwarder',
    'elastic-stack': 'Elastic Stack',
    elasticsearch: 'Elasticsearch',
    'elasticsearch-client': 'Elasticsearch Client',
    'elasticsearch-client-go': 'Elasticsearch Go Client',
    'elasticsearch-client-java': 'Elasticsearch Java Client',
    'elasticsearch-client-javascript': 'Elasticsearch JavaScript Client',
    'elasticsearch-client-dotnet': 'Elasticsearch .NET Client',
    'elasticsearch-client-php': 'Elasticsearch PHP Client',
    'elasticsearch-client-python': 'Elasticsearch Python Client',
    'elasticsearch-client-ruby': 'Elasticsearch Ruby Client',
    'elasticsearch-client-rust': 'Elasticsearch Rust Client',
    'elasticsearch-hadoop': 'Elasticsearch for Apache Hadoop',
    ess: 'Elastic Cloud Hosted',
    filebeat: 'Filebeat',
    fleet: 'Fleet',
    'fleet-server': 'Fleet Server',
    heartbeat: 'Heartbeat',
    integrations: 'Elastic integrations',
    kibana: 'Kibana',
    logstash: 'Logstash',
    'machine-learning': 'Machine Learning',
    metricbeat: 'Metricbeat',
    observability: 'Elastic Observability',
    packetbeat: 'Packetbeat',
    painless: 'Painless',
    'search-ui': 'Search UI',
    security: 'Elastic Security',
    self: 'Self-managed Elastic',
    'serverless-elasticsearch': 'Elasticsearch Serverless',
    'serverless-observability': 'Elastic Observability Serverless',
    'serverless-security': 'Elastic Security Serverless',
    winlogbeat: 'Winlogbeat',
}

/**
 * Get the display name for a product ID
 * Falls back to the ID itself if no display name is found
 */
export function getProductDisplayName(productId: string): string {
    return PRODUCT_DISPLAY_NAMES[productId] ?? productId
}
