// Licensed to Elasticsearch B.V under one or more agreements.
// Elasticsearch B.V licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information

using System.IO.Abstractions;
using Actions.Core.Services;
using Elastic.Documentation;
using Elastic.Documentation.Assembler.Building;
using Elastic.Documentation.Configuration;
using Elastic.Documentation.Configuration.Assembler;
using Elastic.Documentation.Diagnostics;
using Elastic.Documentation.Services;
using Microsoft.Extensions.Logging;
using Nullean.Argh;

namespace Documentation.Builder.Commands.Assembler;

internal sealed class AssemblerSitemapCommand(
	ILoggerFactory logFactory,
	IDiagnosticsCollector collector,
	AssemblyConfiguration configuration,
	IConfigurationContext configurationContext,
	ICoreService githubActionsService
)
{
	/// <summary>Generate <c>sitemap.xml</c> using accurate <c>content_last_updated</c> dates from Elasticsearch.</summary>
	/// <remarks>
	/// <para>
	/// The sitemap generated by <c>assembler build</c> uses the current date as a placeholder.
	/// Run this command after <c>assembler index</c> to overwrite it with precise last-modified dates
	/// sourced from the search index.
	/// </para>
	/// <code>
	/// docs-builder assembler sitemap --endpoint https://es:9200 --api-key KEY --environment staging
	/// </code>
	/// </remarks>
	/// <param name="environment">Named deployment target; used to resolve the correct Elasticsearch index.</param>
	[CommandName("sitemap")]
	public async Task<int> Sitemap(
		GlobalCliOptions _,
		[AsParameters] ElasticsearchIndexOptions es,
		string? environment = null,
		CancellationToken ct = default
	)
	{
		await using var serviceInvoker = new ServiceInvoker(collector);
		var fs = FileSystemFactory.RealWrite;
		var service = new AssemblerSitemapService(logFactory, configuration, configurationContext, githubActionsService);
		serviceInvoker.AddCommand(service,
			async (s, col, ctx) => await s.GenerateSitemapAsync(col, fs, es, environment, ctx)
		);
		return await serviceInvoker.InvokeAsync(ct);
	}
}
