// Licensed to Elasticsearch B.V under one or more agreements.
// Elasticsearch B.V licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information

using Actions.Core.Services;
using Elastic.Documentation;
using Elastic.Documentation.Assembler.Deploying;
using Elastic.Documentation.Configuration;
using Elastic.Documentation.Configuration.Assembler;
using Elastic.Documentation.Diagnostics;
using Elastic.Documentation.Services;
using Microsoft.Extensions.Logging;
using Nullean.Argh;

namespace Documentation.Builder.Commands.Assembler;

internal sealed class DeployCommands(
	AssemblyConfiguration assemblyConfiguration,
	IDiagnosticsCollector collector,
	IConfigurationContext configurationContext,
	ILoggerFactory logFactory,
	ICoreService githubActionsService
)
{
	/// <summary>Create a sync plan for deploying built documentation to S3.</summary>
	/// <param name="environment">The environment to deploy to</param>
	/// <param name="s3BucketName">The S3 bucket name to deploy to</param>
	/// <param name="out">The file path to write the plan to</param>
	/// <param name="deleteThreshold">Maximum percentage of deletions allowed in the plan (as a float)</param>
	[NoOptionsInjection]
	public async Task<int> Plan(string environment, string s3BucketName, string @out = "", float? deleteThreshold = null, CancellationToken ct = default)
	{
		await using var serviceInvoker = new ServiceInvoker(collector);

		var service = new IncrementalDeployService(logFactory, assemblyConfiguration, configurationContext, githubActionsService, FileSystemFactory.RealRead, FileSystemFactory.RealWrite);
		serviceInvoker.AddCommand(service, (environment, s3BucketName, @out, deleteThreshold),
			static async (s, collector, state, ctx) => await s.Plan(collector, state.environment, state.s3BucketName, state.@out, state.deleteThreshold, ctx)
		);
		return await serviceInvoker.InvokeAsync(ct);
	}

	/// <summary>Apply a previously generated sync plan to deploy documentation to S3.</summary>
	/// <param name="environment">The environment to deploy to</param>
	/// <param name="s3BucketName">The S3 bucket name to deploy to</param>
	/// <param name="planFile">Path to the plan file generated by <c>assembler deploy plan</c></param>
	[NoOptionsInjection]
	public async Task<int> Apply(string environment, string s3BucketName, string planFile, CancellationToken ct = default)
	{
		await using var serviceInvoker = new ServiceInvoker(collector);

		var service = new IncrementalDeployService(logFactory, assemblyConfiguration, configurationContext, githubActionsService, FileSystemFactory.RealRead, FileSystemFactory.RealWrite);
		serviceInvoker.AddCommand(service, (environment, s3BucketName, planFile),
			static async (s, collector, state, ctx) => await s.Apply(collector, state.environment, state.s3BucketName, state.planFile, ctx)
		);
		return await serviceInvoker.InvokeAsync(ct);
	}

	/// <summary>Refresh the redirects mapping in CloudFront's KeyValueStore.</summary>
	/// <param name="environment">The environment whose redirects to update</param>
	/// <param name="redirectsFile">Path to the redirects mapping pre-generated by <c>assembler build</c></param>
	[NoOptionsInjection]
	public async Task<int> UpdateRedirects(string environment, string? redirectsFile = null, CancellationToken ct = default)
	{
		await using var serviceInvoker = new ServiceInvoker(collector);

		var fs = FileSystemFactory.RealRead;
		var service = new DeployUpdateRedirectsService(logFactory, fs);
		serviceInvoker.AddCommand(service, (environment, redirectsFile),
			static async (s, collector, state, ctx) => await s.UpdateRedirects(collector, state.environment, state.redirectsFile, ctx: ctx)
		);
		return await serviceInvoker.InvokeAsync(ct);
	}
}
