---
# This workflow is used to build the link-index-updater
# lambda function bootstrap binary that can be deployed to AWS Lambda.
name: Build Link Index Updater Lambda

on:
  workflow_dispatch: 
  workflow_call: 
    inputs:
      ref:
        required: false
        type: string
        default: ${{ github.ref }}
    outputs:
      artifact-id:
        description: 'Artifact ID of the uploaded artifact. Can be used to download the artifact in other workflows.'
        value: ${{ jobs.build.outputs.artifact-id }}

jobs: 
  build:
    outputs: 
      artifact-id: ${{ steps.upload-artifact.outputs.artifact-id }}
      zip-file: ${{ steps.create-zip.outputs.zip-file }}
    runs-on: ubuntu-latest
    env:
      BINARY_PATH: .artifacts/docs-lambda-index-publisher/release_linux-x64/bootstrap
    steps:
      - uses: actions/checkout@v4
        with: 
          ref: ${{ inputs.ref }}
      - name: Amazon Linux 2023 build
        run: |
          docker build . -t publish-links-index:latest -f src/infra/docs-lambda-index-publisher/lambda.DockerFile
      - name: Get bootstrap binary
        run: |
          docker cp $(docker create --name tc publish-links-index:latest):/app/.artifacts/publish ./.artifacts && docker rm tc
      - name: Inspect bootstrap binary
        run: |
          tree .artifacts
          stat "${BINARY_PATH}"
      - name: Archive artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: link-index-updater-lambda-binary
          retention-days: 1
          if-no-files-found: error
          path: ${{ env.BINARY_PATH }}
