name: "Deploy API Lambda (edge)"

on:
  push:
    branches:
      - main

permissions:
  contents: read
  
jobs: 
  deploy:
    uses: ./.github/workflows/deploy-api-lambda.yml
    permissions: 
      id-token: write
      contents: read
    with:
      environment: edge
