name: Docs

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions: {}

concurrency:
  group: docs-${{ github.event_name == 'pull_request' && format('pr{0}', github.event.pull_request.number) || 'main' }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    if: github.event.repository.fork == false
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Build documentation
        uses: elastic/docs-builder@main
        with:
          prefix: docs-builder

      - name: Upload pages artifact
        if: github.event_name == 'push'
        uses: actions/upload-pages-artifact@v5.0.0
        with:
          path: .artifacts/docs/html

  deploy:
    if: github.event_name == 'push' && github.event.repository.fork == false
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    concurrency:
      group: deploy-to-github-pages
      cancel-in-progress: false
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5.0.0
