name: PR

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
         - ubuntu-latest
         - macos-latest
         - windows-latest
    steps:          
      - uses: actions/checkout@v4

      - name: Bootstrap Action Workspace
        id: bootstrap
        uses: ./.github/actions/bootstrap

      - name: Build
        run: dotnet run --project build -c release

      - name: Test
        run: dotnet run --project build -c release -- test

      - name: Publish AOT
        run: dotnet run --project build -c release -- publishbinaries
