name: PR

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  validate-navigation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Bootstrap Action Workspace
        id: bootstrap
        uses: ./.github/actions/bootstrap

      - name: Build
        run: dotnet run --project src/docs-assembler -c release -- navigation validate

  build-lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Amazon Linux 2023 build
        run: |
          docker build . -t publish-links-index:latest -f src/infra/docs-lambda-index-publisher/lambda.DockerFile
      - name: Get bootstrap binary
        run: |
          docker cp $(docker create --name tc publish-links-index:latest):/app/.artifacts/publish ./.artifacts && docker rm tc
          tree .artifacts
          stat .artifacts/docs-lambda-index-publisher/release_linux-x64/bootstrap

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
         - ubuntu-latest
         - macos-latest
         - windows-latest
    steps:          
      - uses: actions/checkout@v4

      - name: Bootstrap Action Workspace
        id: bootstrap
        uses: ./.github/actions/bootstrap

      - name: Build
        run: dotnet run --project build -c release

      - name: Test
        run: dotnet run --project build -c release -- test

      - name: Publish AOT
        run: dotnet run --project build -c release -- publishbinaries
