name: PR

on:
  pull_request:

permissions:
  contents: read
  packages: read
  id-token: write
  pull-requests: write
  deployments: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Bootstrap Action Workspace
        id: bootstrap
        uses: ./.github/actions/bootstrap

      - name: Build
        run: ./build.sh

      - name: Test
        run: ./build.sh test

      - name: Publish AOT
        run: ./build.sh publishbinaries

      # we run our artifact directly please use the prebuild
      # elastic/docs-builder@main GitHub Action for all other repositories!
      - name: Build documentation
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: .artifacts/publish/docs-builder/release/docs-builder --strict --path-prefix "/${GITHUB_REPOSITORY}/pull/${PR_NUMBER}"
      
      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: .artifacts/docs/html
          if-no-files-found: error
          retention-days: 1

  preview:
    needs: build
    uses: ./.github/workflows/preview.yml
