name: PR

on:
  pull_request:

permissions:
  contents: read
  packages: read
  id-token: write
  pull-requests: write
  deployments: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v4

      - name: Bootstrap Action Workspace
        id: bootstrap
        uses: ./.github/actions/bootstrap

      - name: Build
        run: ./build.sh

      - name: Test
        run: ./build.sh test

      - name: Publish AOT
        run: ./build.sh publishbinaries
        
      - uses: actions/upload-artifact@v4
        if: matrix.os == 'ubuntu-latest'
        with:
          name: docs-builder-binary
          path: .artifacts/publish/docs-builder/release/docs-builder
          if-no-files-found: error
          retention-days: 1

  build-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v4

      - name: Bootstrap Action Workspace
        id: bootstrap
        uses: ./.github/actions/bootstrap

      - name: Test
        shell: cmd
        run: build.bat test

      - name: Publish AOT
        shell: cmd
        run: build.bat publishbinaries
