name: PR

on:
  pull_request:

permissions:
  contents: read
  packages: read
  id-token: write
  pull-requests: write
  deployments: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Bootstrap Action Workspace
        id: bootstrap
        uses: ./.github/actions/bootstrap

      - name: Run Analyzers
        run: |
          dotnet format analyzers --severity info -v diag --verify-no-changes --report .artifacts/report.json || true && \
             cat .artifacts/report.json | jq -r '.[] | "::warning file=\(.FilePath),line=\(.FileChanges[].LineNumber),endLine=\(.FileChanges[].LineNumber),title=\(.FileChanges[].DiagnosticId)::\(.FileChanges[].FormatDescription)"' | sort | uniq

      - name: Build
        run: ./build.sh

      - name: Test
        run: ./build.sh test

      - name: Publish AOT
        run: ./build.sh publishbinaries
        
      - uses: actions/upload-artifact@v4
        with:
          name: docs-builder-binary
          path: .artifacts/publish/docs-builder/release/docs-builder
          if-no-files-found: error
          retention-days: 1
