name: Pre-release main branch

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    outputs:
      full-version: ${{ steps.bootstrap.outputs.full-version }}
      major-version: ${{ steps.bootstrap.outputs.major-version }}
    needs: [build]
    concurrency: 
      group: deploy-to-github-pages

    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - id: repo-basename
        run: 'echo "value=`basename ${{ github.repository }}`" >> $GITHUB_OUTPUT'
      - uses: actions/checkout@v6.0.3
        with:
          persist-credentials: false
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v6.0.0
      - name: Build documentation
        uses: elastic/docs-builder@main
        with:
          prefix: '${{ steps.repo-basename.outputs.value }}'
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5.0.0
        with:
          path: .artifacts/docs/html
          
      - name: Deploy artifact
        id: deployment
        uses: actions/deploy-pages@v5.0.0 
        
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      full-version: ${{ steps.bootstrap.outputs.full-version }}
      major-version: ${{ steps.bootstrap.outputs.major-version }}

    steps:
      - uses: actions/checkout@v6.0.3
        with:
          persist-credentials: false

      - name: Bootstrap Action Workspace
        id: bootstrap
        uses: ./.github/actions/bootstrap
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Publish Containers
        run: ./build.sh publishcontainers
