name: preview-cleanup

on:
  workflow_call: ~
  pull_request_target:
    types: [closed]

permissions:
  deployments: write
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: elastic/docs-builder/.github/actions/aws-auth@main
      - name: Delete s3 objects
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
            aws s3 rm "s3://elastic-docs-v3-website-preview/${GITHUB_REPOSITORY}/pull/${PR_NUMBER}" --recursive

      - name: Delete GitHub environment
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const deployments = await github.rest.repos.listDeployments({
              owner,
              repo,
              environment: `docs-preview-${context.issue.number}`
            });
            for (const deployment of deployments.data) {
              await github.rest.repos.createDeploymentStatus({
                owner,
                repo,
                deployment_id: deployment.id,
                state: 'inactive',
                description: 'Marking deployment as inactive'
              });
              await github.rest.repos.deleteDeployment({
                owner,
                repo,
                deployment_id: deployment.id
              });
            }

    
            
