name: release-drafter

on:
  workflow_dispatch: ~
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  update-release-draft:
    concurrency:
      group: release-drafter
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@eada3c96a64734dd381cfbda23511034e328ddb0 # v7.6.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
