name: required-labels

on:
  pull_request_target:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize

permissions:
  contents: read

jobs:
  check-labels:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: get-labels
        run: |
          labels=$(yq '[.categories[].labels] + .exclude-labels | flatten | unique | sort | @tsv' .github/release-drafter.yml | tr '\t' ',')
          echo "labels=$labels" >> "${GITHUB_OUTPUT}"
      - id: check-labels
        uses: mheap/github-action-required-labels@388fd6af37b34cdfe5a23b37060e763217e58b03 # v5.5
        with:
          mode: exactly
          count: 1
          use_regex: false
          add_comment: true
          labels: ${{ steps.get-labels.outputs.labels }}
