name: smoke-tests

on:
  pull_request: ~
  
env:
  PATH_PREFIX: /docs
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: 
        include:
          - repository: elastic/docs-content
            first-page-path-output: /docs/
          - repository: elastic/apm-agent-android
            first-page-path-output: /docs/reference/
            
            # This is a random repository that should not have a docset.yml
          - repository: elastic/oblt-actions
            first-page-path-output: ""

    steps:
      - uses: actions/checkout@v4
      - name: Bootstrap Action Workspace
        uses: ./.github/actions/bootstrap
        
      - uses: actions/checkout@v4
        with:
          repository: ${{ matrix.repository }}
          path: test-repo

      - name: Build documentation
        id: docs-build
        run: |
          dotnet run --project src/docs-builder -- --strict --path-prefix "/docs" -p test-repo
      
      - name: Verify first page path
        run: test ${{ steps.docs-build.outputs.first-page-path }} == ${{ matrix.first-page-path-output }}
